# Generated by Django 4.2.26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='McpConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('scalable', 'Scalable Capital')], max_length=32)),
                ('mcp_server_url', models.URLField(help_text='z.B. https://mcp.scalable.capital/mcp')),
                ('authorization_endpoint', models.URLField(blank=True)),
                ('token_endpoint', models.URLField(blank=True)),
                ('registration_endpoint', models.URLField(blank=True)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('scopes', models.CharField(default='openid profile offline_access', max_length=255)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Besitzer der Verbindung', on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MCP-Verbindung',
                'verbose_name_plural': 'MCP-Verbindungen',
                'ordering': ['provider'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
