# Generated by Django 4.2.26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpconnection',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text="Zeitpunkt des letzten erfolgreichen Live-Checks (initialize-Handshake) gegen den MCP-Server. Einzige Quelle für 'verbunden' — DB-persistiert statt Browser-Session, damit Status und Anzeige immer übereinstimmen und ein Seitenwechsel/-besuch keinen erneuten Login braucht.", null=True),
        ),
    ]
