# Generated by Django 4.2.26 on 2026-10-07 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ausgabe', 'Ausgabe'), ('einzahlung', 'Einzahlung')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(blank=True, choices=[('karte', 'Karte'), ('bar', 'Bar')], max_length=8)),
                ('note', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Toern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Törn',
                'verbose_name_plural': 'Törns',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('qty', models.CharField(blank=True, max_length=24)),
                ('info', models.CharField(blank=True, max_length=60)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einkaufsliste', to='bordkasse.toern')),
            ],
            options={
                'verbose_name': 'Einkaufslisten-Eintrag',
                'verbose_name_plural': 'Einkaufsliste',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='bordkasse.toern')),
            ],
            options={
                'verbose_name': 'Crew-Mitglied',
                'verbose_name_plural': 'Crew',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BuchungRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ausgabe', 'Ausgabe'), ('einzahlung', 'Einzahlung')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(blank=True, choices=[('karte', 'Karte'), ('bar', 'Bar')], max_length=8)),
                ('note', models.CharField(blank=True, max_length=80)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('buchung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisionen', to='bordkasse.buchung')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bordkasse.crewmember')),
            ],
            options={
                'verbose_name': 'Buchungs-Revision',
                'verbose_name_plural': 'Buchungs-Revisionen',
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='buchung',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bordkasse.crewmember'),
        ),
        migrations.AddField(
            model_name='buchung',
            name='toern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchungen', to='bordkasse.toern'),
        ),
        migrations.AddConstraint(
            model_name='crewmember',
            constraint=models.UniqueConstraint(fields=('toern', 'name'), name='bordkasse_crew_unique_name'),
        ),
    ]
