# Generated by Django 4.2.26 on 2026-10-08 08:16

from django.db import migrations, models


def create_konfig(apps, schema_editor):
    BordkasseKonfig = apps.get_model('bordkasse', 'BordkasseKonfig')
    if not BordkasseKonfig.objects.exists():
        BordkasseKonfig.objects.create(authentifizierung_erforderlich=False)


class Migration(migrations.Migration):

    dependencies = [
        ('bordkasse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BordkasseKonfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentifizierung_erforderlich', models.BooleanField(db_column='Authentifizierung_erforderlich', default=False, help_text='Aktiv: Alle Seiten unter /bordkasse/ (auch Ansehen und Einkaufsliste) nur nach Login.', verbose_name='Authentifizierung erforderlich')),
            ],
            options={
                'verbose_name': 'Bordkasse-Konfiguration',
                'verbose_name_plural': 'Bordkasse-Konfiguration',
                'db_table': 'Bordkasse_Konfig',
            },
        ),
        migrations.RunPython(create_konfig, migrations.RunPython.noop),
    ]
