# Generated by Django 4.2.26 on 2026-10-08 08:31

from django.db import migrations, models
import django.db.models.deletion


# Stand der bisher im Code (services.STANDARD_LIST) gepflegten Liste — wird einmalig übernommen.
STANDARDLISTE = [
    ('Frühstück', ['Brot/Brötchen', 'Butter', 'Margarine', 'Marmelade', 'Honig', 'Müsli', 'H-Milch',
                   'Eier', 'Kaffee', 'Tee', 'Orangensaft', 'Speck', 'Wurst', 'Käse']),
    ('Mittagessen', ['Nudeln', 'Tomatensauce', 'Pesto', 'Thunfisch (Dose)', 'Reis', 'Knäckebrot']),
    ('Abendessen', ['Hack', 'Hähnchenbrust', 'Dorade', 'Paprika', 'Zucchini', 'Tomaten', 'Pilze',
                    'Gurke', 'Salat', 'Kartoffeln', 'Zwiebeln', 'Knoblauch', 'Olivenöl', 'Öl',
                    'Essig', 'Salz & Pfeffer', 'Gewürzmischung']),
    ('Obst', ['Melonen', 'Äpfel', 'Bananen', 'Pfirsiche', 'Weintrauben']),
    ('Getränke', ['Wasser still', 'Wasser medium', 'Bier', 'Bier alkoholfrei', 'Weißwein', 'Rotwein',
                  'Prosecco', 'Aperol', 'Cola', 'Cola Zero', 'Limo', 'Limo Zero', 'Säfte']),
    ('Snacks', ['Chips', 'Salzgebäck', 'Nüsse', 'Kekse', 'Schokolade', 'Müsliriegel']),
    ('Sonstiges', ['Toilettenpapier', 'Küchenrolle', 'Spülmittel', 'Schwämme', 'Müllbeutel',
                   'Kaffeefilter']),
]


def seed_standardliste(apps, schema_editor):
    Kategorie = apps.get_model('bordkasse', 'StandardKategorie')
    Artikel = apps.get_model('bordkasse', 'StandardArtikel')
    for k_pos, (kategorie, artikel) in enumerate(STANDARDLISTE, start=1):
        k, _ = Kategorie.objects.get_or_create(name=kategorie, defaults={'position': k_pos * 10})
        for a_pos, name in enumerate(artikel, start=1):
            Artikel.objects.get_or_create(kategorie=k, name=name, defaults={'position': a_pos * 10})


class Migration(migrations.Migration):

    dependencies = [
        ('bordkasse', '0002_bordkasse_konfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Reihenfolge, kleinere Zahl zuerst.')),
            ],
            options={
                'verbose_name': 'Standardlisten-Kategorie',
                'verbose_name_plural': 'Standardliste',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StandardArtikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('position', models.PositiveIntegerField(default=0, help_text='Reihenfolge, kleinere Zahl zuerst.')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artikel', to='bordkasse.standardkategorie')),
            ],
            options={
                'verbose_name': 'Standardlisten-Artikel',
                'verbose_name_plural': 'Standardlisten-Artikel',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='standardartikel',
            constraint=models.UniqueConstraint(fields=('kategorie', 'name'), name='bordkasse_standardartikel_unique'),
        ),
        migrations.RunPython(seed_standardliste, migrations.RunPython.noop),
    ]
