# Generated by Django 4.2.26 on 2026-01-22 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False, verbose_name='Gelesen')),
            ],
            options={
                'verbose_name': 'Kontakt-Nachricht',
                'verbose_name_plural': 'Kontakt-Nachrichten',
                'ordering': ['-created_at'],
            },
        ),
    ]
