# Generated by Django 4.2.26 on 2026-01-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistChessMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('German', 'German'), ('English', 'English'), ('Spanish', 'Spanish'), ('Other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Historical Chess Magazine',
                'ordering': ['name'],
            },
        ),
    ]
