# Generated by Django 4.2.26 on 2026-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='headline',
            field=models.CharField(max_length=64),
        ),
    ]
