# Generated by Django 4.2.26 on 2026-01-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_blogpost_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='external_url',
            field=models.URLField(blank=True, help_text="Wenn gesetzt, führt 'Read more' direkt hierhin statt auf die Detailseite.", null=True),
        ),
    ]
