# Generated by Django 4.2.26 on 2026-01-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_blogpost_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='external_url',
            field=models.URLField(blank=True, help_text="If set, 'Read more' leads here (External). If empty, it loads the template based on the slug.", null=True),
        ),
    ]
