# Generated by Django 4.2.26 on 2026-04-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_blogpost_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='black_listed',
            field=models.BooleanField(default=False, verbose_name='Blacklist'),
        ),
    ]
