# Generated by Django 4.2.26 on 2026-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(help_text='Morgen oder Abend', verbose_name='Datum')),
                ('systolisch', models.PositiveIntegerField(verbose_name='Systolisch (oberer Wert)')),
                ('diastolisch', models.PositiveIntegerField(verbose_name='Diastolisch (unterer Wert)')),
                ('herzschlag', models.PositiveIntegerField(verbose_name='Herzschlag (bpm)')),
                ('info', models.BooleanField(default=False, help_text='Messwerte-Info markieren', verbose_name='Info-Flag')),
            ],
            options={
                'verbose_name': 'Blutdruckmessung',
                'verbose_name_plural': 'Blutdruckmessungen',
                'ordering': ['-datum'],
            },
        ),
    ]
