# Generated by Django 4.2.26 on 2026-03-16 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodpressure',
            options={'ordering': ['-datum_zeit'], 'verbose_name': 'Blutdruckmessung', 'verbose_name_plural': 'Blutdruckmessungen'},
        ),
        migrations.RemoveField(
            model_name='bloodpressure',
            name='datum',
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='datum_zeit',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Morgen/Abend + Uhrzeit', verbose_name='Datum & Uhrzeit'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='info',
            field=models.CharField(blank=True, help_text='Zusätzliche Notizen (max. 256 Zeichen)', max_length=256, verbose_name='Info-Notiz'),
        ),
    ]
