# Generated by Django 4.2.26 on 2026-03-29 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_bloodpressure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolisch',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)], verbose_name='Diastolisch (unterer Wert)'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='herzschlag',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='Herzschlag (bpm)'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolisch',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(300)], verbose_name='Systolisch (oberer Wert)'),
        ),
    ]
