# Generated by Django 4.2.26 on 2026-02-02 10:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('isin', models.CharField(help_text='Internationale Wertpapierkennnummer (12 Zeichen)', max_length=12, primary_key=True, serialize=False, verbose_name='ISIN')),
                ('wkn', models.CharField(blank=True, help_text='Wertpapierkennnummer (6 Zeichen, hauptsächlich für deutsche Werte)', max_length=6, null=True, unique=True)),
                ('symbol', models.CharField(blank=True, help_text='Börsenkürzel (z.B. AAPL, SAP)', max_length=10, null=True)),
                ('name', models.CharField(help_text='Vollständiger Name des Assets/Unternehmens', max_length=200)),
                ('asset_class', models.CharField(choices=[('STOCK', 'Aktie'), ('ETF', 'ETF'), ('ETC', 'ETC'), ('CRYPTO', 'Kryptowährung'), ('DERIVATIVE', 'Derivat')], default='STOCK', help_text='Art des Assets', max_length=10)),
                ('currency', models.CharField(default='EUR', help_text='Währung als ISO-Code (EUR, USD, etc.)', max_length=3)),
                ('exchange', models.CharField(blank=True, help_text='Hauptbörse (XETRA, NYSE, NASDAQ, etc.)', max_length=50, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, help_text='Letzter bekannter Kurs (Cache)', max_digits=12, null=True)),
                ('current_price_timestamp', models.DateTimeField(blank=True, help_text='Zeitpunkt des letzten Kurses', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Zeitpunkt der Kursfeststellung')),
                ('amount', models.DecimalField(decimal_places=4, help_text='Kurs in Währung des Assets', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='fintech.asset')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurse',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, help_text='Anzahl gehaltener Anteile (auch Bruchteile möglich)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('average_purchase_price', models.DecimalField(blank=True, decimal_places=4, help_text='Durchschnittlicher Einkaufspreis', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.IntegerField(blank=True, choices=[(1, 'Basis Investment'), (2, 'Dividende'), (3, 'D/EU'), (4, 'US Tech'), (5, 'World Tech'), (6, 'Compounder'), (99, 'Sonstiges')], default=99, help_text='Kategorie der Investment-Strategie', null=True)),
                ('notes', models.TextField(blank=True, help_text='Persönliche Notizen zu dieser Position', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='fintech.asset')),
            ],
            options={
                'verbose_name': 'Bestand',
                'verbose_name_plural': 'Bestände',
                'ordering': ['-quantity'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_class'], name='fintech_ass_asset_c_73ce07_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['symbol'], name='fintech_ass_symbol_2a329d_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['asset', '-timestamp'], name='fintech_pri_asset_i_8fdda3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('asset', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='holdings',
            unique_together={('asset',)},
        ),
    ]
