# Generated by Django 4.2.26 on 2026-02-02 11:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='amount',
        ),
        migrations.AddField(
            model_name='price',
            name='current_price',
            field=models.DecimalField(decimal_places=4, default=162, help_text='Kurs in Währung des Assets zum Zeitpunkt ...', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
            preserve_default=False,
        ),
    ]
