# Generated by Django 4.2.26 on 2026-03-29 10:37

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fintech', '0002_remove_price_amount_price_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name der Watchlist (z.B. 'US Tech Favoriten')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Besitzer der Watchlist', on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('CHF', 'CHF'), ('GBP', 'GBP'), ('GBp', 'GBp'), ('JPY', 'JPY'), ('NOK', 'NOK'), ('CAD', 'CAD'), ('DKK', 'DKK'), ('SEK', 'SEK'), ('AUD', 'AUD')], default='EUR', help_text='Währung als ISO-Code (EUR, USD, etc.)', max_length=3),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Basis Investment'), (2, 'Dividende'), (3, 'D/EU'), (4, 'US Tech'), (5, 'World Tech'), (6, 'Compounder'), (7, 'Defence'), (8, 'Robotics'), (9, 'Cybersecurity'), (10, 'Software'), (11, 'Healthcare'), (12, 'AI Input'), (13, 'Banking'), (99, 'Sonstiges')], default=99, help_text='Kategorie der Investment-Strategie', null=True),
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Zeitpunkt der Aufnahme in Watchlist')),
                ('price_at_add', models.DecimalField(decimal_places=4, help_text='Kurs zum Zeitpunkt der Aufnahme', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('notes', models.CharField(blank=True, help_text='Grund für Watchlist-Aufnahme (optional)', max_length=200)),
                ('asset', models.ForeignKey(help_text='Beobachtetes Asset', on_delete=django.db.models.deletion.CASCADE, to='fintech.asset')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fintech.watchlist')),
            ],
            options={
                'verbose_name': 'Watchlist-Eintrag',
                'verbose_name_plural': 'Watchlist-Einträge',
                'ordering': ['added_at'],
                'indexes': [models.Index(fields=['watchlist', 'added_at'], name='fintech_wat_watchli_c45e38_idx'), models.Index(fields=['asset'], name='fintech_wat_asset_i_740627_idx')],
                'unique_together': {('watchlist', 'asset')},
            },
        ),
    ]
