# Generated by Django 4.2.26 on 2026-03-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0003_watchlist_alter_asset_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isin', models.CharField(max_length=12)),
                ('category_display', models.CharField(max_length=50)),
                ('total_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('delta_abs', models.DecimalField(decimal_places=2, max_digits=20)),
                ('delta_perc', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Übersicht',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('CHF', 'CHF'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('NOK', 'NOK'), ('CAD', 'CAD'), ('DKK', 'DKK'), ('SEK', 'SEK'), ('AUD', 'AUD')], default='EUR', help_text='Währung als ISO-Code (EUR, USD, etc.)', max_length=3),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Basis Investment'), (2, 'Dividende'), (3, 'D/EU'), (4, 'US Tech'), (5, 'World Tech'), (6, 'Compounder'), (7, 'Defence'), (8, 'Robotics'), (9, 'Cybersecurity'), (10, 'Software'), (11, 'Healthcare'), (12, 'AI Input'), (13, 'Finance'), (99, 'Sonstiges')], default=99, help_text='Kategorie der Investment-Strategie', null=True),
        ),
    ]
