# Generated by Django 4.2.26 on 2026-03-29 15:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0004_portfoliosummary_alter_asset_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliosummary',
            options={'managed': False, 'verbose_name': 'Portfolio Position', 'verbose_name_plural': 'Portfolio Übersicht'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('CHF', 'CHF'), ('GBP', 'GBP'), ('GBp', 'GBp'), ('JPY', 'JPY'), ('NOK', 'NOK'), ('CAD', 'CAD'), ('DKK', 'DKK'), ('SEK', 'SEK'), ('AUD', 'AUD')], default='EUR', help_text='Währung als ISO-Code (EUR, USD, etc.)', max_length=3),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='average_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Durchschnittlicher Einkaufspreis', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
