# Generated by Django 4.2.26 on 2026-03-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0005_alter_portfoliosummary_options_alter_asset_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Basis Investment'), (2, 'Dividende'), (3, 'D/EU'), (4, 'US Tech'), (5, 'World Tech'), (6, 'Compounder'), (7, 'Defence'), (8, 'Robotics'), (9, 'Cybersecurity'), (10, 'Software'), (11, 'Healthcare'), (12, 'AI Input'), (13, 'Finance'), (14, 'Crypto'), (99, 'Sonstiges')], default=1, help_text='Kategorie der Investment-Strategie', null=True),
        ),
    ]
