# Generated by Django 4.2.26 on 2026-04-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0006_alter_holdings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(choices=[('STOCK', 'Aktie'), ('ETF', 'ETF'), ('ETC', 'ETC'), ('CRYPTO', 'Kryptowährung'), ('DERIVATIVE', 'Derivat'), ('FOND', 'Fond')], default='STOCK', help_text='Art des Assets', max_length=10),
        ),
    ]
