# Generated by Django 4.2.26 on 2026-06-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0011_data_resolve_asset_names_and_prices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlistentry',
            options={'ordering': ['-added_at'], 'verbose_name': 'Watchlist-Eintrag', 'verbose_name_plural': 'Watchlist-Einträge'},
        ),
    ]
