# Generated by Django 4.2.26 on 2026-06-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0013_data_category_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Basis Investment'), (2, 'Dividende'), (3, 'D/EU'), (4, 'US Tech'), (5, 'World Tech'), (6, 'Compounder'), (7, 'Defence'), (8, 'Robotics'), (9, 'Cybersecurity'), (10, 'Software'), (11, 'Healthcare'), (12, 'AI Input'), (13, 'Finance'), (14, 'Crypto'), (99, 'Sonstiges'), (20, 'Insurance'), (21, 'Finance Global'), (22, 'EU Technology'), (23, 'US Big Tech'), (24, 'Cybersecurity & Cloud'), (25, 'Defense'), (26, 'Energy'), (27, 'AI & Robotics'), (28, 'Pharma & Biotech'), (29, 'Cars'), (30, 'Consumer & Brands'), (31, 'Infrastructure'), (32, 'Mining & Resources'), (33, 'Precious Metals & Bonds'), (34, 'Crypto & Blockchain'), (35, 'Core Investment'), (36, 'Asia & Emerging Markets'), (37, 'Chemicals')], default=1, help_text='Kategorie der Investment-Strategie', null=True),
        ),
    ]
