# Generated by Django 4.2.26 on 2026-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0014_alter_holdings_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='logo',
            field=models.URLField(blank=True, help_text='Logo-URL, z.B. https://s3-symbol-logo.tradingview.com/iberdrola--big.svg', null=True),
        ),
    ]
