# Generated by Django 4.2.26 on 2026-06-05 13:01

from django.db import migrations, models

ISIN_CATEGORY_MAP = {
    'US69121K1043': 21,  # Blue Owl Capital       → Finance Global
    'US0995021062': 25,  # Booz Allen Hamilton    → Defense
    'FR0011648716': 37,  # Carbios                → Chemicals
    'DE000A2YN355': 22,  # Circus SE              → EU Technology
    'FR0014003TT8': 25,  # Dassault Systèmes      → Defense
    'DE000A161N30': 21,  # Grenke                 → Finance Global
    'DE0005493365': 21,  # Hypoport               → Finance Global
    'DE0006231004': 22,  # Infineon Technologies  → EU Technology
    'DE000A3E00M1': 22,  # Ionos Group            → EU Technology
    'US6541061031': 30,  # NIKE                   → Consumer & Brands
    'DE000HS2Q0E3': 35,  # Mini-Future HSBC       → Core Investment
    'DE0006969603': 30,  # PUMA                   → Consumer & Brands
    'US79466L3024': 24,  # Salesforce             → Cybersecurity & Cloud
    'CNE100006CQ4': 27,  # UBTECH Robotics        → AI & Robotics
    'DE000A1ML7J1': 31,  # Vonovia                → Infrastructure
    'LU0274211480': 35,  # Xtrackers DAX (Acc)    → Core Investment
}


def assign_remaining_categories(apps, schema_editor):
    Asset = apps.get_model('fintech', 'Asset')
    Holdings = apps.get_model('fintech', 'Holdings')
    updated = 0
    skipped = []
    for isin, cat in ISIN_CATEGORY_MAP.items():
        try:
            asset = Asset.objects.get(isin=isin)
        except Asset.DoesNotExist:
            skipped.append(isin)
            continue
        n = Holdings.objects.filter(asset=asset).update(category=cat)
        updated += n
    if skipped:
        print(f"\n  Warnung: {len(skipped)} ISINs nicht gefunden: {skipped}")
    print(f"\n  {updated} Holdings auf neue Kategorien migriert.")


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0015_asset_logo'),
    ]

    operations = [
        migrations.RunPython(assign_remaining_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='holdings',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Basis Investment'), (2, 'Dividende'), (3, 'D/EU'), (4, 'US Tech'), (5, 'World Tech'), (6, 'Compounder'), (7, 'Defence'), (8, 'Robotics'), (9, 'Cybersecurity'), (10, 'Software'), (11, 'Healthcare'), (12, 'AI Input'), (13, 'Finance'), (14, 'Crypto'), (99, 'Sonstiges'), (20, 'Insurance'), (21, 'Finance Global'), (22, 'EU Technology'), (23, 'US Big Tech'), (24, 'Cybersecurity & Cloud'), (25, 'Defense'), (26, 'Energy'), (27, 'AI & Robotics'), (28, 'Pharma & Biotech'), (29, 'Cars'), (30, 'Consumer & Brands'), (31, 'Infrastructure'), (32, 'Mining & Resources'), (33, 'Precious Metals & Bonds'), (34, 'Crypto & Blockchain'), (35, 'Core Investment'), (36, 'Asia & Emerging Markets'), (37, 'Chemicals'), (38, 'Miscellaneous')], default=1, help_text='Kategorie der Investment-Strategie', null=True),
        ),
    ]
