# Generated by Django 4.2.26 on 2026-06-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0016_category_miscellaneous_and_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='category',
            field=models.IntegerField(blank=True, choices=[(20, 'Insurance'), (21, 'Finance Global'), (22, 'EU Technology'), (23, 'US Big Tech'), (24, 'Cybersecurity & Cloud'), (25, 'Defense'), (26, 'Energy'), (27, 'AI & Robotics'), (28, 'Pharma & Biotech'), (29, 'Cars'), (30, 'Consumer & Brands'), (31, 'Infrastructure'), (32, 'Mining & Resources'), (33, 'Precious Metals & Bonds'), (34, 'Crypto & Blockchain'), (35, 'Core Investment'), (36, 'Asia & Emerging Markets'), (37, 'Chemicals'), (38, 'Miscellaneous')], default=38, help_text='Kategorie der Investment-Strategie', null=True),
        ),
    ]
