# Generated by Django 4.2.26 on 2026-06-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0017_remove_legacy_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(blank=True, help_text='TradingView-Symbol (z.B. XETR:RHM, NASDAQ:AAPL)', max_length=20, null=True),
        ),
    ]
