# Generated by Django 4.2.26 on 2026-06-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0021_fiftytwoweeekrange_yahoo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiftytwoweekrange',
            name='week52_high',
            field=models.DecimalField(decimal_places=4, help_text='52-Wochen-Hoch in Yahoo-Währung', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fiftytwoweekrange',
            name='week52_low',
            field=models.DecimalField(decimal_places=4, help_text='52-Wochen-Tief in Yahoo-Währung', max_digits=12),
        ),
    ]
